name: ComponentCodeOfConduct
description: $description
version: '${version}'

main: me.biquaternions.componentcodeofconduct.ComponentCodeOfConduct
bootstrapper: me.biquaternions.componentcodeofconduct.ComponentCodeOfConductBootstrap
api-version: '26.1'
load: STARTUP

authors: [ Biquaternions ]
